// Generated by website-builder from design-repo/tokens/ (source: https://www.daylit.com/). Tailwind v3. Do not hand-edit; re-run the scrape.
// Values are measured from computed styles; names are heuristic. Nothing here overrides Tailwind's default scales.
// Breakpoints: bp-<px> = min-width, bp-max-<px> = max-width (measured from the site's CSS media queries).
export default {
  corePlugins: { preflight: false }, // the site's own CSS is the reset
  "content": [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx,html}"
  ],
  "theme": {
    "extend": {
      "colors": {
        "red-01": "rgb(77,21,32)",
        "red-02": "rgb(130,87,91)",
        "neutral-01": "rgb(251,249,246)",
        "orange-01": "rgb(242,238,231)",
        "yellow-01": "rgb(250,255,167)",
        "neutral-02": "rgb(0,0,0)",
        "red-03": "rgb(130,91,99)",
        "orange-02": "rgb(211,202,195)",
        "neutral-03": "rgb(255,255,255)",
        "neutral-04": "rgb(170,164,159)",
        "red-04": "rgb(92,26,26)",
        "neutral-05": "rgb(254,255,225)",
        "red-05": "rgb(74,58,58)",
        "red-06": "rgb(44,31,31)",
        "neutral-06": "rgb(103,101,101)",
        "neutral-07": "rgb(221,221,221)",
        "orange-03": "rgb(221,120,2)",
        "pink-01": "rgb(102,47,61)",
        "red-07": "rgb(54,9,18)",
        "orange-04": "rgb(221,213,200)",
        "neutral-08": "rgb(255,251,235)",
        "orange-05": "rgb(233,227,216)",
        "green-01": "rgb(167,193,120)",
        "neutral-09": "rgb(249,245,240)",
        "orange-06": "rgb(242,235,225)",
        "red-08": "rgb(48,26,28)",
        "orange-07": "rgb(242,237,232)",
        "yellow-02": "rgb(255,255,125)",
        "neutral-10": "rgb(25,24,24)",
        "red-09": "rgb(180,35,24)",
        "neutral-11": "rgb(254,243,242)",
        "green-02": "rgb(209,232,174)",
        "red-10": "rgb(70,16,28)",
        "neutral-12": "rgb(14,9,31)",
        "neutral-13": "rgb(12,6,7)",
        "neutral-14": "rgb(122,106,106)",
        "neutral-15": "rgb(217,216,219)",
        "green-03": "rgb(234,244,238)",
        "green-04": "rgb(30,107,58)",
        "neutral-16": "rgb(138,122,122)",
        "neutral-17": "rgb(243,240,238)",
        "neutral-18": "rgb(232,232,232)",
        "orange-08": "rgb(181,129,58)",
        "neutral-19": "rgb(246,243,243)",
        "orange-09": "rgb(244,234,225)",
        "neutral-20": "rgb(248,247,242)",
        "neutral-21": "rgb(251,250,244)",
        "red-11": "rgba(130,91,99,0.75)",
        "neutral-22": "rgb(121,107,105)",
        "orange-10": "rgb(138,90,0)",
        "neutral-23": "rgb(253,243,227)",
        "neutral-24": "rgb(47,8,15)",
        "orange-11": "rgb(232,224,208)",
        "orange-12": "rgb(245,240,232)",
        "orange-13": "rgb(255,132,61)",
        "red-12": "rgb(61,26,26)",
        "orange-14": "rgb(245,237,231)",
        "neutral-25": "rgb(245,248,250)",
        "blue-01": "rgb(33,45,58)",
        "red-13": "rgb(76,20,31)",
        "surface-default": "rgb(250,255,167)",
        "surface-alt": "rgb(255,255,255)",
        "surface-inverse": "rgb(170,164,159)",
        "surface-accent": "rgb(250,255,167)",
        "text-primary": "rgb(77,21,32)",
        "text-secondary": "rgb(130,87,91)",
        "text-inverse": "rgb(251,249,246)",
        "text-accent": "rgb(77,21,32)",
        "border-default": "rgb(242,238,231)",
        "accent-primary": "rgb(77,21,32)"
      },
      "spacing": {
        "sp-2": "2px",
        "sp-3": "3px",
        "sp-4": "4px",
        "sp-6": "6px",
        "sp-8": "8px",
        "sp-10": "10px",
        "sp-12": "12px",
        "sp-13": "13px",
        "sp-14": "14px",
        "sp-16": "16px",
        "sp-18": "18px",
        "sp-20": "20px",
        "sp-22": "22px",
        "sp-24": "24px",
        "sp-26": "26px",
        "sp-30": "30px",
        "sp-32": "32px",
        "sp-40": "40px",
        "sp-48": "48px",
        "sp-57_5938": "57.5938px",
        "sp-60": "60px",
        "sp-64": "64px",
        "sp-88": "88px",
        "sp-128": "128px",
        "gutter": "60px"
      },
      "borderRadius": {
        "r-6": "6px",
        "r-1_85": "1.85px",
        "r-1440": "1440px",
        "r-2": "2px",
        "r-4": "4px",
        "r-8": "8px",
        "r-20": "20px",
        "r-24": "24px",
        "r-1000": "1000px",
        "r-10": "10px",
        "control": "6px",
        "surface": "1.85px",
        "pill": "1440px"
      },
      "boxShadow": {
        "e-01": "rgba(0, 0, 0, 0.1) 0px 4px 20px 0px",
        "e-02": "rgba(92, 26, 26, 0.07) 0px 2px 10px 0px",
        "e-03": "rgb(250, 255, 167) 0px 0px 0px 6px",
        "e-04": "rgb(242, 238, 231) 0px 0px 0px 1px",
        "e-05": "rgba(0, 0, 0, 0.1) 0px 2px 13px 0px",
        "e-06": "rgba(0, 0, 0, 0.5) 0px 24px 60px 0px",
        "elev-default": "rgba(0, 0, 0, 0.1) 0px 4px 20px 0px"
      },
      "fontFamily": {
        "ff-01": [
          "\"Tt Commons Pro Variable\"",
          "sans-serif"
        ],
        "ff-02": [
          "\"Source Sans 3\"",
          "sans-serif"
        ],
        "ff-03": [
          "\"Geist Mono\"",
          "sans-serif"
        ],
        "ff-04": [
          "\"Lora\"",
          "sans-serif"
        ],
        "ff-05": [
          "\"TT Commons Pro\"",
          "sans-serif"
        ],
        "ff-06": [
          "\"helvetica\"",
          "sans-serif"
        ],
        "ff-07": [
          "\"Helvetica\"",
          "sans-serif"
        ],
        "ff-08": [
          "\"Open Sans\"",
          "sans-serif"
        ],
        "display": [
          "\"Tt Commons Pro Variable\"",
          "sans-serif"
        ],
        "heading": [
          "\"Tt Commons Pro Variable\"",
          "sans-serif"
        ],
        "body": [
          "\"Tt Commons Pro Variable\"",
          "sans-serif"
        ],
        "label": [
          "\"Tt Commons Pro Variable\"",
          "sans-serif"
        ]
      },
      "fontSize": {
        "fs-11": "11px",
        "fs-12": "12px",
        "fs-13": "13px",
        "fs-14": "14px",
        "fs-15": "15px",
        "fs-15_5": "15.5px",
        "fs-16": "16px",
        "fs-16_5": "16.5px",
        "fs-18": "18px",
        "fs-19": "19px",
        "fs-20": "20px",
        "fs-24": "24px",
        "fs-28": "28px",
        "fs-32": "32px",
        "fs-44": "44px",
        "fs-48": "48px",
        "fs-56": "56px",
        "fs-76": "76px",
        "display": [
          "56px",
          {
            "lineHeight": "64.4px",
            "fontWeight": "500"
          }
        ],
        "heading": [
          "20px",
          {
            "lineHeight": "28px",
            "fontWeight": "500"
          }
        ],
        "body": [
          "18px",
          {
            "lineHeight": "23.94px",
            "fontWeight": "500"
          }
        ],
        "label": [
          "16px",
          {
            "lineHeight": "23.94px",
            "fontWeight": "500"
          }
        ]
      },
      "transitionDuration": {
        "d-200ms": "0.2s",
        "d-350ms": "0.35s",
        "d-1200ms": "1.2s",
        "d-250ms": "0.25s",
        "d-300ms": "0.3s",
        "d-500ms": "0.5s",
        "d-50ms": "0.05s",
        "d-150ms": "0.15s",
        "motion-default": "0.2s"
      },
      "transitionTimingFunction": {
        "ease-01": "ease",
        "ease-02": "cubic-bezier(0.165, 0.84, 0.44, 1)",
        "ease-03": "cubic-bezier(0.47, 0, 0.745, 0.715)",
        "ease-04": "linear",
        "ease-05": "cubic-bezier(0.645, 0.045, 0.355, 1)",
        "ease-06": "ease-out",
        "motion-default": "ease"
      },
      "screens": {
        "bp-400": {
          "min": "400px"
        },
        "bp-430": {
          "min": "430px"
        },
        "bp-640": {
          "min": "640px"
        },
        "bp-768": {
          "min": "768px"
        },
        "bp-992": {
          "min": "992px"
        },
        "bp-1200": {
          "min": "1200px"
        },
        "bp-1280": {
          "min": "1280px"
        },
        "bp-1320": {
          "min": "1320px"
        },
        "bp-1440": {
          "min": "1440px"
        },
        "bp-1920": {
          "min": "1920px"
        },
        "bp-max-1200": {
          "max": "1200px"
        },
        "bp-max-991": {
          "max": "991px"
        },
        "bp-max-768": {
          "max": "768px"
        },
        "bp-max-767": {
          "max": "767px"
        },
        "bp-max-600": {
          "max": "600px"
        },
        "bp-max-479": {
          "max": "479px"
        }
      },
      "maxWidth": {
        "content": "1440px"
      }
    }
  },
  "plugins": []
};
